GM.Config = GM.Config or {}

GM.Config["sv_gravity"]          = "800"
GM.Config["sv_airaccelerate"]    = "20"
GM.Config["sv_sticktoground"]    = "0"
GM.Config["sv_accelerate"]       = "10"
GM.Config["sv_friction"]         = "4"
GM.Config["sv_stopspeed"]        = "100"
GM.Config["hl1_sv_clampammo"]    = "1"
GM.Config["hl1_sv_cmodels"]       = "0"
GM.Config["hl1_sv_cmodels"]       = "0"
GM.Config["sv_gsrchud_allow_deathcam"] = "0"
GM.Config["gsrchud_skipempty"] = "0"

GM.Config["hl1_sk_plr_dmg_crowbar"]          = "25"
GM.Config["hl1_sk_plr_dmg_9mm_bullet"]       = "12"
GM.Config["hl1_sk_plr_dmg_357_bullet"]       = "50"
GM.Config["hl1_sk_plr_dmg_mp5_bullet"]       = "12"
GM.Config["hl1_sk_plr_dmg_buckshot"]         = "20"
GM.Config["hl1_sk_plr_dmg_rpg"]              = "120"
GM.Config["hl1_sk_plr_dmg_xbow_bolt_plr"]    = "20"
GM.Config["hl1_sk_plr_dmg_hornet"]           = "10"
GM.Config["hl1_sk_plr_dmg_egon_wide"]        = "20"
GM.Config["hl1_sk_plr_dmg_grenade"]          = "100"
GM.Config["hl1_sk_plr_dmg_satchel"]          = "150"
GM.Config["hl1_sk_plr_dmg_tripmine"]         = "150"